server:
  error:
    include-message: always
  port: 8180
spring:
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
application:
  reader:
    max-allowed-book: 4
